       IDENTIFICATION DIVISION.
       PROGRAM-ID. MAIN.
       DATA DIVISION.
       FILE SECTION.
       WORKING-STORAGE SECTION.
       PROCEDURE DIVISION.
       MAIN.
            DISPLAY "PAYROLL MANAGEMENT SYSTEM"
            STOP RUN.
       END PROGRAM MAIN.

